'use strict';
const $ = id => document.getElementById(id);
const escapeText = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const concepts = {
 numbers:{title:'Numbers around us',notes:['Numbers describe how many objects are in a group.','Counting pairs each object with one number word. The last number tells you the total.','Adding brings groups together. Subtracting tells you what remains.'],example:'There are 3 pencils on a desk. Add 2 more pencils: 3 + 2 = 5 pencils.',question:'There are 3 pencils. You add 2. How many are there?',options:['4','5','6'],answer:1,explanation:'Count on two steps from 3: 4, then 5.'},
 shapes:{title:'Shapes and patterns',notes:['A triangle has three sides. A quadrilateral has four sides.','A repeating pattern follows a rule that you can use to predict the next item.','Turn a shape to see whether its sides and corners stay the same.'],example:'The pattern circle, square, circle, square repeats every two shapes.',question:'What comes next: circle, square, circle, square, …?',options:['Triangle','Square','Circle'],answer:2,explanation:'The two-shape block repeats, so a circle comes next.'},
 fractions:{title:'Understanding fractions',notes:['A fraction describes equal parts of a whole.','The denominator tells you how many equal parts make the whole. The numerator counts the selected parts.','Equivalent fractions name the same amount: one half is equal to two quarters.'],example:'Cut a sandwich into 4 equal pieces. If you take 3, you have 3/4 of the sandwich.',question:'Which fraction is equal to 1/2?',options:['1/4','2/4','3/4'],answer:1,explanation:'Two of four equal pieces cover the same amount as one of two equal pieces.'},
 algebra:{title:'Thinking with algebra',notes:['A variable stands for a number that may be unknown or change.','An equation states that two expressions have the same value.','Perform the same operation on both sides to keep an equation balanced.'],example:'For x + 3 = 7, subtract 3 from both sides. This gives x = 4.',question:'What is x when x + 3 = 7?',options:['3','4','10'],answer:1,explanation:'Subtract 3 from both sides: x = 7 − 3 = 4.'},
 functions:{title:'Relations and functions',notes:['A function assigns exactly one output to each allowed input.','The domain is the set of allowed inputs.','A formula, table, or graph can describe a function.'],example:'For f(x) = 2x + 1, the input 3 gives f(3) = 7.',question:'If f(x) = 2x + 1, what is f(3)?',options:['6','7','9'],answer:1,explanation:'Substitute 3 for x: 2 × 3 + 1 = 7.'},
 plants:{title:'How plants make food',notes:['Photosynthesis uses light energy to make glucose from carbon dioxide and water.','Chlorophyll helps leaves absorb light.','Oxygen is released during photosynthesis. Plants also respire.'],example:'A green plant with water and carbon dioxide uses light to make sugars that support growth.',question:'Which gas is used as a raw material in photosynthesis?',options:['Oxygen','Carbon dioxide','Nitrogen'],answer:1,explanation:'Carbon dioxide supplies carbon for the sugars made during photosynthesis.'},
 food:{title:'Food and nutrition',notes:['Food supplies energy and materials needed for growth and repair.','Different foods provide different nutrients, so variety matters.','Carbohydrates and fats supply energy; proteins support growth and repair.'],example:'A meal containing rice, lentils, vegetables, and curd brings together several kinds of nutrients.',question:'Which nutrient is especially associated with growth and tissue repair?',options:['Protein','Water alone','Fibre alone'],answer:0,explanation:'Proteins supply amino acids used to build and repair body tissues.'},
 water:{title:'Water around us',notes:['Heating can change liquid water into water vapour.','Cooling water vapour can form liquid droplets through condensation.','The water cycle includes evaporation, condensation, and precipitation.'],example:'Drops on the outside of a cold glass form when water vapour in the surrounding air condenses.',question:'What is the change from water vapour to liquid water called?',options:['Evaporation','Condensation','Melting'],answer:1,explanation:'Condensation turns a gas into liquid droplets.'},
 motion:{title:'Motion and measurement',notes:['A measurement needs both a number and a unit.','Speed compares distance travelled with time taken.','For uniform motion, speed = distance ÷ time.'],example:'A cyclist covers 60 metres in 10 seconds at a steady speed: 60 ÷ 10 = 6 m/s.',question:'A cyclist travels 60 m in 10 s. What is the average speed?',options:['6 m/s','60 m/s','600 m/s'],answer:0,explanation:'Average speed is total distance divided by total time: 60 ÷ 10 = 6 m/s.'},
 electricity:{title:'Electric circuits',notes:['Current is the rate of flow of electric charge.','A simple circuit needs a complete conducting path for steady current to flow.','For an ohmic conductor under constant physical conditions, V = IR.'],example:'A 6 V potential difference across a 3 Ω ohmic resistor produces a current of 2 A.',question:'For V = 6 V and R = 3 Ω, what current does V = IR predict?',options:['18 A','2 A','0.5 A'],answer:1,explanation:'Rearrange V = IR to I = V/R. Then I = 6/3 = 2 A.'},
 atoms:{title:'Atoms and molecules',notes:['Atoms are the basic units of chemical elements.','A molecule contains atoms held together by chemical bonds.','A chemical formula tells you the elements present and their proportions.'],example:'H₂O represents a water molecule containing two hydrogen atoms and one oxygen atom.',question:'How many hydrogen atoms are in one H₂O molecule?',options:['One','Two','Three'],answer:1,explanation:'The subscript 2 after H specifies two hydrogen atoms.'},
 cells:{title:'Cells and living things',notes:['Cells are the basic structural and functional units of living organisms.','A cell membrane separates the cell from its surroundings and regulates exchange.','Plant cells typically have a cell wall in addition to the cell membrane.'],example:'An onion peel contains many cells. Under a microscope, their boundaries can be observed.',question:'Which structure is typical of plant cells but absent in animal cells?',options:['Cell membrane','Cell wall','Cytoplasm'],answer:1,explanation:'Plant cells have a cell wall; animal cells do not.'},
 reading:{title:'Reading for meaning',notes:['Look for the main idea before focusing on small details.','Use surrounding words to work out unfamiliar vocabulary.','Support your interpretation with evidence from the passage.'],example:'If a passage describes a dry river, empty wells, and worried farmers, those details may support a main idea about drought.',question:'What best supports an interpretation of a passage?',options:['A guess unrelated to the text','Relevant evidence from the passage','The length of the passage'],answer:1,explanation:'An interpretation is stronger when it points to relevant words or events in the text.'},
 writing:{title:'Building clear sentences',notes:['A sentence expresses a complete thought.','Clear writing connects ideas in a logical order.','Review punctuation and word choice after drafting.'],example:'“The rain stopped. We went outside.” gives two complete thoughts in a clear sequence.',question:'What should you do after drafting a paragraph?',options:['Review clarity and punctuation','Remove every full stop','Add unrelated ideas'],answer:0,explanation:'Revision helps readers follow your ideas.'},
 poetry:{title:'Exploring a poem',notes:['Read a poem aloud to notice rhythm and sound.','Imagery uses language to help a reader imagine a sensory experience.','Different interpretations need support from the words in the poem.'],example:'“The leaves whispered” gives a human action to leaves. This is personification.',question:'“The leaves whispered” is an example of what?',options:['A measurement','Personification','A date'],answer:1,explanation:'Whispering is a human action attributed to leaves.'}
};
function catalog(grade){
 const primary=grade<=5,senior=grade>=11;
 return [
  {id:'math',name:'Mathematics',icon:'x²',color:'#e9efff',topics:grade<=2?['numbers','shapes','fractions']:grade<=7?['fractions','shapes','algebra']:['algebra','functions','fractions']},
  {id:'science',name:senior?'Physics':primary?'Our World':'Science',icon:senior?'V = IR':'↗',color:'#e6f3f0',topics:senior?['electricity','motion','atoms']:primary?['plants','water','food']:['food','plants','motion']},
  {id:'language',name:senior?'Biology':'English',icon:senior?'Aa':'Aa',color:'#fff0e3',topics:senior?['cells','plants','food']:['reading','writing','poetry']}
 ];
}
let state={grade:6,book:'science',chapter:0,tool:'tutor',started:false,messages:[],card:0,flipped:false,quizAnswer:null};
function book(){return catalog(state.grade).find(b=>b.id===state.book)}
function concept(){return concepts[book().topics[state.chapter]]}
function announce(text){$('announce').textContent=text}
function resetChapter(){Object.assign(state,{tool:'tutor',started:false,messages:[],card:0,flipped:false,quizAnswer:null})}
function renderClasses(){ $('classes').innerHTML=Array.from({length:12},(_,i)=>`<button class="class-choice ${state.grade===i+1?'selected':''}" data-grade="${i+1}" aria-pressed="${state.grade===i+1}" aria-label="Class ${i+1}"><small>CLASS</small><strong>${i+1}</strong></button>`).join(''); $('stage-label').textContent=state.grade<=5?'Primary school':state.grade<=8?'Middle school':state.grade<=10?'Secondary school':'Senior secondary';$('classes').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.grade=Number(b.dataset.grade);state.book='math';state.chapter=0;resetChapter();render();announce(`Class ${state.grade} selected. Book and chapter reset.`)})}
function renderBooks(){const books=catalog(state.grade);$('book-count').textContent=`${books.length} sample books`;$('books').innerHTML=books.map(b=>`<button class="book ${b.id===state.book?'selected':''}" data-book="${b.id}" aria-pressed="${b.id===state.book}" aria-label="${b.name} sample book"><div class="book-cover" style="--cover:${b.color}"><small>CLASS ${state.grade} / SAMPLE</small><span class="subject-icon" aria-hidden="true">${b.icon}</span></div><div class="book-bottom"><div><h3>${b.name}</h3><p>English · Topic preview</p></div><span class="book-check" aria-hidden="true">✓</span></div></button>`).join('');$('books').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.book=b.dataset.book;state.chapter=0;resetChapter();renderBooks();renderChapters();renderStudy();announce(`${book().name} selected.`)})}
function renderChapters(){const b=book();$('chapter-count').textContent=`${b.topics.length} sample chapters`;$('chapters').innerHTML=b.topics.map((id,i)=>`<button class="chapter ${state.chapter===i?'selected':''}" data-chapter="${i}" aria-pressed="${state.chapter===i}"><span class="chapter-num">${String(i+1).padStart(2,'0')}</span><div><h3>${concepts[id].title}</h3><p>Sample topic · Source not connected</p></div><span class="chapter-arrow" aria-hidden="true">↗</span></button>`).join('');$('chapters').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.chapter=Number(b.dataset.chapter);resetChapter();renderChapters();renderStudy();announce(`${concept().title} selected. Tutor and study tools updated.`)})}
function renderStudy(){const c=concept();$('study-context').innerHTML=`<h2 id="study-heading">${c.title}</h2><div class="context-meta">Class ${state.grade} <span aria-hidden="true">/</span> ${book().name}<br>Authored sample · Not a textbook extract</div>`;$('tool-tabs').querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.tool===state.tool);b.setAttribute('aria-pressed',String(b.dataset.tool===state.tool));b.onclick=()=>{state.tool=b.dataset.tool;renderStudy()}});if(state.tool==='tutor')renderTutor();if(state.tool==='notes')renderNotes();if(state.tool==='cards')renderCards();if(state.tool==='quiz')renderQuiz()}
function renderTutor(){const el=$('tool-content'),c=concept();if(!state.started){el.innerHTML=`<div class="tutor-start"><div class="tutor-icon" aria-hidden="true">✦</div><h3>A little help, right where you are.</h3><p>Explore ${c.title.toLowerCase()} with a simple explanation and a worked example.</p><button class="primary wide" id="start-tutor">Open tutor demo →</button><p class="disclaimer">This is a scripted preview, not a live AI conversation. It uses sample learning material, not verified NCERT pages.</p></div>`;$('start-tutor').onclick=()=>{state.started=true;state.messages=[{role:'tutor',text:`Let’s explore ${c.title.toLowerCase()}. ${c.notes[0]}\n\nChoose an explanation, example, or practice question below.`}];renderTutor();$('tutor-question').focus()};return}
 el.innerHTML=`<div class="chat-log" id="chat-log" role="log" aria-label="Tutor conversation">${state.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':''}"><small>${m.role==='user'?'You':'Tutor · scripted demo'}</small>${escapeText(m.text)}</div>`).join('')}</div><div class="prompts"><button data-prompt="Explain simply">Explain simply</button><button data-prompt="Show an example">Show an example</button><button data-prompt="Give me practice">Give me practice</button></div><form class="chat-form" id="chat-form"><label class="sr-only" for="tutor-question">Ask about this chapter</label><input id="tutor-question" maxlength="500" placeholder="Ask about this chapter…" required><button class="primary" aria-label="Send question">↑</button></form><p class="disclaimer">Demo replies only. Live AI and page-linked textbook citations are not connected.</p>`;
 el.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));$('chat-form').onsubmit=e=>{e.preventDefault();send($('tutor-question').value)};$('chat-log').scrollTop=$('chat-log').scrollHeight;
}
function send(raw){const text=raw.trim();if(!text)return;const c=concept();let reply;if(/example/i.test(text))reply=c.example;else if(/practice|quiz|test/i.test(text))reply=`Try this: ${c.question}\n\n${c.options.map((o,i)=>`${String.fromCharCode(65+i)}. ${o}`).join('\n')}\n\nOpen Quick quiz to answer and check the explanation.`;else if(/explain|summary|summarize|simple/i.test(text))reply=c.notes.join('\n\n');else reply=`Your question has reached the tutor workflow for “${c.title}”. This preview cannot generate a live answer.\n\nA useful starting point from the sample lesson: ${c.notes[0]}\n\nTry “Explain simply” or “Show an example” to explore this demo.`;state.messages.push({role:'user',text},{role:'tutor',text:reply});state.messages=state.messages.slice(-20);renderTutor();$('tutor-question').focus()}
function renderNotes(){const c=concept();$('tool-content').innerHTML=`<div class="tool-heading"><h3>Your chapter, at a glance</h3><span>Sample notes</span></div><ul class="notes-list">${c.notes.map(n=>`<li>${n}</li>`).join('')}</ul><div class="quiz-feedback"><strong>Try to explain it back</strong><p>${c.example}</p></div><p class="disclaimer">These authored notes illustrate the study-tool workflow. They are not extracted from an NCERT textbook.</p>`}
function renderCards(){const c=concept();const cards=[{q:c.question,a:c.options[c.answer]},{q:'Explain the main idea in your own words.',a:c.notes[0]},{q:'Give one example of this concept.',a:c.example}];state.card=Math.min(state.card,cards.length-1);const item=cards[state.card];$('tool-content').innerHTML=`<div class="tool-heading"><h3>Recall before you reveal</h3><span>${state.card+1} / ${cards.length}</span></div><button class="flashcard" id="flashcard" aria-label="${state.flipped?'Show question':'Reveal answer'}"><small>${state.flipped?'ANSWER':'QUESTION'}</small>${escapeText(state.flipped?item.a:item.q)}</button><p class="disclaimer">Tap the card to ${state.flipped?'see the question':'reveal the answer'}.</p><div class="card-controls"><button class="secondary" id="prev-card" ${state.card===0?'disabled':''}>← Previous</button><button class="secondary" id="next-card" ${state.card===cards.length-1?'disabled':''}>Next →</button></div>`;$('flashcard').onclick=()=>{state.flipped=!state.flipped;renderCards()};$('prev-card').onclick=()=>{state.card--;state.flipped=false;renderCards()};$('next-card').onclick=()=>{state.card++;state.flipped=false;renderCards()}}
function renderQuiz(){const c=concept(),answered=state.quizAnswer!==null;$('tool-content').innerHTML=`<div class="tool-heading"><h3>One quick check</h3><span>Sample question</span></div><p class="tool-copy">${c.question}</p><div class="quiz-options">${c.options.map((o,i)=>`<button class="quiz-option ${answered?(i===c.answer?'correct':i===state.quizAnswer?'wrong':''):''}" data-answer="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>${answered?`<div class="quiz-feedback" role="status"><strong>${state.quizAnswer===c.answer?'That’s right.':'Not quite. Let’s work through it.'}</strong><p>${c.explanation}</p></div><button class="secondary" id="retry-quiz" style="margin-top:15px">Try again</button>`:'<p class="disclaimer">Choose an answer to see the reasoning. No grade or progress record is saved.</p>'}`;$('tool-content').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.quizAnswer=Number(b.dataset.answer);renderQuiz()});if(answered)$('retry-quiz').onclick=()=>{state.quizAnswer=null;renderQuiz()}}
function view(source){$('library-view').hidden=source;$('sources-view').hidden=!source;$('library-nav').classList.toggle('active',!source);$('sources-nav').classList.toggle('active',source);$('library-nav').setAttribute('aria-current',source?'false':'page');$('sources-nav').setAttribute('aria-current',source?'page':'false');window.scrollTo({top:0,behavior:'instant'})}
$('library-nav').onclick=()=>{location.hash='library'};$('sources-nav').onclick=$('source-footer').onclick=()=>{location.hash='sources'};$('source-back').onclick=()=>{location.hash='library'};window.addEventListener('hashchange',()=>view(location.hash==='#sources'));
function render(){renderClasses();renderBooks();renderChapters();renderStudy()}
render();view(location.hash==='#sources');
