(() => {
    'use strict';
    const request=(path,body)=>window.StudyStudio.request('roadmaps'+path,body);
    const oldRestore=rmRestore,oldSave=rmSave,oldRender=renderRoadmap;
    let polling=null,readVersion=0;
    const setup=document.getElementById('rm-setup-box'),panel=document.createElement('div');
    panel.className='ss-root ss-cloud';
    panel.innerHTML='<div class="ss-actions"><label class="ss-label">Your saved roadmaps<select id="rm-cloud-list"><option value="">Choose a saved roadmap</option></select></label><button type="button" class="ss-btn" id="rm-cloud-refresh">Refresh</button><button type="button" class="ss-btn" id="rm-cloud-sync">Save browser plan to account</button></div><p class="ss-mini">Account plans continue generating while this tab is closed. Completed days and paused progress are saved on the server.</p><details><summary>Make room for missed days</summary><p class="ss-mini">Pause first. Move unfinished work and the target date forward together; completed days keep their dates.</p><label class="ss-label">Extra calendar days<input type="number" id="rm-shift" value="1" min="1" max="365"></label><button type="button" id="rm-shift-save" class="ss-btn">Reschedule remaining work</button></details>';
    setup.prepend(panel);
    const message=text=>{document.getElementById('rm-save-status').textContent=text;document.getElementById('rm-save-status').setAttribute('role','status');};
    async function list(){if(!authToken)return;const owner=authToken;const {roadmaps}=await request('');if(owner!==authToken)return;const el=document.getElementById('rm-cloud-list');el.replaceChildren(new Option('Choose a saved roadmap',''));for(const r of roadmaps)el.add(new Option(`${r.title} · ${r.ready}/${r.days} days · ${r.status}`,r.id));if(rmCurrentPlan?.cloudId)el.value=rmCurrentPlan.cloudId;return roadmaps;}
    function schedule(){clearTimeout(polling);if(rmCurrentPlan?.cloudId&&['queued','generating'].includes(rmCurrentPlan.state))polling=setTimeout(()=>load(rmCurrentPlan.cloudId).catch(e=>{message(e.message);rmBusy=false;}),2500);}
    async function load(id){const version=++readVersion,owner=authToken;const result=await request('/'+encodeURIComponent(id));if(version!==readVersion||owner!==authToken)return;rmCurrentPlan={...result,cloudId:result.id,ownerKey:rmStorageKey()};rmBusy=['queued','generating'].includes(result.state);renderRoadmap(rmCurrentPlan);schedule();}
    renderRoadmap=function(plan){oldRender(plan);document.getElementById('rm-cloud-sync').hidden=!!plan.cloudId;if(!plan.cloudId)return;document.getElementById('rm-cloud-list').value=plan.cloudId;const busy=['queued','generating'].includes(plan.state);document.getElementById('rm-pause-btn').disabled=!busy;document.getElementById('rm-resume-btn').disabled=busy||plan.complete;document.getElementById('rm-generate-btn').disabled=busy;document.getElementById('rm-generate-status').style.display='block';document.getElementById('rm-generate-status').textContent=plan.error|| (plan.complete?`All ${plan.daysUntil} days are ready.`:busy?`Preparing day ${plan.plan.length+1} onwards. You can close this tab; generation continues on the server.`:'Paused. Your generated days are saved.');message('Saved to your account · available on your other devices.');document.getElementById('rm-cloud-sync').hidden=true;};
    rmRestore=async function(){if(!authToken)return;try{const roadmaps=await list();if(rmCurrentPlan?.cloudId&&rmCurrentPlan.ownerKey===rmStorageKey())return load(rmCurrentPlan.cloudId);if(roadmaps?.length)await load(roadmaps[0].id);else oldRestore();}catch(e){message(e.message+' Browser-saved plans remain available.');oldRestore();}};
    rmSave=function(){if(!rmCurrentPlan?.cloudId)return oldSave();message('Saved to your account.');};
    continueRoadmap=async function(){if(!rmBusy&&rmCurrentPlan)return runRoadmap();};
    runRoadmap=async function(){if(!rmCurrentPlan||!authToken)return;const owner=authToken;try{rmBusy=true;document.getElementById('rm-generate-btn').disabled=true;if(!rmCurrentPlan.cloudId){let result;if(rmCurrentPlan.plan.length)result=await request('/import',rmCurrentPlan);else result=await request('',{...rmCurrentPlan,days:rmCurrentPlan.daysUntil});if(owner!==authToken)return;rmCurrentPlan.cloudId=result.id;if(rmCurrentPlan.plan.length)await request('/'+result.id+'/action',{action:'resume'});}else await request('/'+rmCurrentPlan.cloudId+'/action',{action:'resume'});await load(rmCurrentPlan.cloudId);await list();}catch(e){rmBusy=false;document.getElementById('rm-generate-btn').disabled=false;message(e.message);showToast(e.message,'info');}};
    document.getElementById('rm-cloud-list').onchange=e=>{if(e.target.value)load(e.target.value).catch(e=>message(e.message));};
    document.getElementById('rm-cloud-refresh').onclick=()=>rmRestore();
    document.getElementById('rm-cloud-sync').onclick=async()=>{if(!rmCurrentPlan||rmCurrentPlan.cloudId)return message('Open a browser-saved plan first.');try{const r=await request('/import',rmCurrentPlan);await load(r.id);await list();}catch(e){message(e.message);}};
    document.getElementById('rm-pause-btn').addEventListener('click',async()=>{if(!rmCurrentPlan?.cloudId)return;try{await request('/'+rmCurrentPlan.cloudId+'/action',{action:'pause'});await load(rmCurrentPlan.cloudId);message('Paused. An in-flight batch may finish and will be saved.');setTimeout(()=>{if(rmCurrentPlan?.cloudId)load(rmCurrentPlan.cloudId).catch(()=>{});},5000);}catch(e){message(e.message);}});
    document.getElementById('rm-timeline').addEventListener('change',async e=>{if(!rmCurrentPlan?.cloudId||!e.target.dataset.roadmapDay)return;const id=rmCurrentPlan.cloudId;try{await request('/'+id+'/action',{action:'complete-day',day:Number(e.target.dataset.roadmapDay),completed:e.target.checked});message('Day saved to your account.');}catch(err){message(err.message);await load(id);}});
    document.getElementById('rm-shift-save').onclick=async()=>{if(!rmCurrentPlan?.cloudId)return message('Save this plan to your account first.');try{await request('/'+rmCurrentPlan.cloudId+'/action',{action:'reschedule',shiftDays:Number(document.getElementById('rm-shift').value)});await load(rmCurrentPlan.cloudId);message('Unfinished days and target date moved. The number of learning days is unchanged.');}catch(e){message(e.message);}};
    window.addEventListener('storage',e=>{if(e.key==='authToken'){clearTimeout(polling);++readVersion;rmBusy=false;rmCurrentPlan=null;}});
    if(document.getElementById('study-roadmap').classList.contains('active'))rmRestore();
})();
