(() => {
    'use strict';
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const token=()=>localStorage.getItem('authToken');
    let root,teacherMode=false,classes=[],selectedClass='',pack=null,tab='learn',viewVersion=0,account='',pendingTargets=[],source=null,recognition=null,queuedPack=null;
    const labels={baseline:'Starting check',practice:'Guided practice',followup:'Independent check',retention:'7-day retention'};
    async function request(path,body,method) {
        const owner=token();
        const r=await fetch('/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{Authorization:`Bearer ${owner}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
        const data=await r.json();if(owner!==token())throw new Error('Account changed. Reopen your workspace.');
        if(!r.ok)throw new Error(data.msg||'This action could not be completed.');return data;
    }
    function status(text,error=false){const el=root?.querySelector('.ss-status');if(el){el.textContent=text;el.classList.toggle('ss-error',error);}}
    function shell(title,description,actions='') {
        root.innerHTML=`<header class="ss-head"><div><span class="ss-eyebrow">${teacherMode?'Teaching, connected':'Your learning, connected'}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="ss-actions">${actions}</div></header><p class="ss-status" role="status" aria-live="polite"></p><div class="ss-body"></div>`;
    }
    const btn=(action,label,primary=false,extra='')=>`<button type="button" class="ss-btn ${primary?'ss-primary':''}" data-ss="${action}" ${extra}>${label}</button>`;
    const body=()=>root.querySelector('.ss-body');
    const field=(name,label,value='',type='text',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
    function prose(el,text) { if(typeof renderOutputWithMath==='function')renderOutputWithMath(el,text);else el.textContent=text; }
    function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
    async function open(isTeacher=false) {
        const requestedPack=queuedPack;queuedPack=null;
        teacherMode=isTeacher;root=document.getElementById(isTeacher?'ss-teacher':'ss-student');
        const version=++viewVersion;account=token();pack=null;pendingTargets=[];recognition?.stop();
        shell(isTeacher?'Learning Studio':'Study Studio','One chapter. Clear steps. Progress you can see.');
        if(!account){status('Sign in to open your saved workspace.');return;}
        if(isTeacher){try{classes=(await request('teacher/classes')).classes.filter(c=>c.status==='active');if(version!==viewVersion)return;if(!classes.some(c=>String(c.id)===selectedClass))selectedClass=String(classes[0]?.id||'');}catch(e){status(e.message,true);return;}}
        if(requestedPack){try{await showPack(requestedPack);}catch(e){status(e.message,true);}}else await library(version);
    }
    async function library(version=++viewVersion) {
        pack=null;recognition?.stop();
        shell(teacherMode?'Learning Studio':'Study Studio',teacherMode?'Turn your sources into reviewed lessons, targeted practice and meaningful follow-up.':'Understand a chapter, practice with support, then check what you can do independently.',btn('new','Create study pack',true));
        body().innerHTML=`${teacherMode?`<div class="ss-actions"><label class="ss-label">Classroom<select id="ss-class">${classes.map(c=>`<option value="${c.id}" ${String(c.id)===selectedClass?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${btn('sources','Source library')}${btn('insights','Class insights')}</div>`:''}<div class="ss-note">${teacherMode?'Draft → review → assign → check → follow up. Published packs keep the source and answer key version you approved.':'Your lessons, revision cards and checks stay together. Start with a short check so you can compare your progress later.'}</div><div id="ss-pack-list" class="ss-grid"></div>`;
        if(teacherMode)root.querySelector('#ss-class').onchange=e=>{selectedClass=e.target.value;library();};
        status('Loading your saved packs…');
        try{
            const data=await request('studio/packs');if(version!==viewVersion||account!==token())return;
            const packs=data.packs.filter(p=>!teacherMode||String(p.class_id)===selectedClass);
            const list=root.querySelector('#ss-pack-list');
            list.innerHTML=packs.map(p=>`<article class="ss-card ss-pack"><span class="ss-pill">${p.status==='draft'?'Draft · review needed':p.owner?'Your pack':'Assigned by teacher'}</span><h3>${esc(p.title)}</h3><p>${esc(p.meta.grade)} ${esc(p.meta.subject)} · ${esc(p.meta.language)}</p><span class="ss-mini">${p.due_date?'Due '+esc(p.due_date):esc(p.meta.sourceName)}</span>${teacherMode?'':`<div class="ss-meter" aria-label="${p.progress.length} of 4 checks completed"><span style="width:${p.progress.length*25}%"></span></div>`}<div class="ss-actions">${btn('pack',p.status==='draft'?'Review pack':teacherMode?'View approved pack':'Continue learning',false,`data-id="${p.id}"`)}${teacherMode?'':`<span class="ss-mini">${p.progress.length}/4 checks</span>`}</div></article>`).join('');
            if(!packs.length){list.className='ss-empty';list.innerHTML='<span class="ss-eyebrow">A focused place to begin</span><h2 style="margin-top:12px">Make your first chapter yours.</h2><p>Bring a topic or teacher-approved source. Build a lesson, worked example, cards and four connected checks.</p><div class="ss-actions">'+btn('new','Create study pack',true)+(!teacherMode?btn('labs','Explore learning labs'):'')+'</div>';}
            status(packs.length?`${packs.length} saved pack${packs.length===1?'':'s'}.`:'');
        }catch(e){status(e.message,true);}
    }
    async function createForm(prefill={}) {
        ++viewVersion;pack=null;
        shell('A chapter, made clear.','Start with the material you trust. You can review every part before using it.',btn('library','Back to packs'));
        const cls=classes.find(c=>String(c.id)===selectedClass);
        body().innerHTML=`<form id="ss-create" class="ss-form ss-card"><div class="ss-two">${field('title','Chapter or goal',prefill.title||'','text','required maxlength="200" placeholder="e.g. Motion — distance and displacement"')}${field('subject','Subject',cls?.subject||'Science','text','required maxlength="100"')}</div><div class="ss-two">${field('grade','Class / level',cls?.grade||'Class 9','text','maxlength="40"')}${field('board','Board / curriculum','CBSE','text','maxlength="60"')}</div><div class="ss-two">${field('edition','Book title and edition','','text','maxlength="150" placeholder="As printed in your textbook"')}<label>Explanation language<select name="language"><option>Hindi / Hinglish</option><option>English</option><option>Hindi</option></select></label></div>${teacherMode?`<label>Reviewed class source<select name="resourceId" id="ss-resource-select"><option value="">Use pasted text or a general topic</option></select></label>`:''}<label>Source text or specific learning requirements<textarea name="sourceText" rows="6" maxlength="24000" placeholder="Paste the relevant material or describe what you want to learn. Textbook alignment is only as reliable as the material provided.">${esc(prefill.sourceText||'')}</textarea></label><label>Or extract text from a file<input id="ss-source-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.docx,.pptx,.txt,.md,.csv"></label>${btn('extract-personal','Read file into source text')}<p class="ss-mini">Extraction is a draft. Review the text above before creating a pack. Up to 6 MB; only the first 24,000 characters are copied into this field.</p>${teacherMode?field('preparationMinutes','Preparation time so far, minutes (optional)','','number','min="0" max="240" step="1"'):''}<div class="ss-note">${teacherMode?'This creates a private draft for your review. Select the learners only after checking the lesson and answer keys.':'AI creates a draft. Check its content against your source before approving it for personal practice.'} Edition labels you enter are not independent verification.</div><div class="ss-actions"><button class="ss-btn ss-primary" type="submit">Create draft</button><span class="ss-mini">Saved to your account</span></div></form>`;
        const createdVersion=viewVersion;
        if(teacherMode&&selectedClass){try{const {resources}=await request(`studio/classes/${selectedClass}/sources`);if(createdVersion!==viewVersion)return;root.querySelector('#ss-resource-select').innerHTML+=resources.filter(r=>r.status==='reviewed').map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.status)}</option>`).join('');}catch(e){status(e.message,true);}}
        const form=root.querySelector('#ss-create');
        form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),data=Object.fromEntries(f);data.classId=teacherMode?Number(selectedClass):null;data.preparationMinutes=data.preparationMinutes?Number(data.preparationMinutes):null;perform(e.submitter,async()=>{if(teacherMode&&!selectedClass)throw new Error('Create a classroom first in My Classes.');status('Creating your lesson, worked example and distinct assessment questions…');const result=await request('studio/packs',data);if(createdVersion===viewVersion)await showPack(result.id);});};
    }
    async function showPack(id) {
        const version=++viewVersion;
        status('Opening your chapter…');
        const p=await request('studio/packs/'+encodeURIComponent(id));if(version!==viewVersion)return;
        pack=p;tab='learn';renderPack();
        if(p.editable&&p.classId){const data=await request(`studio/classes/${p.classId}/insights`);if(version===viewVersion)renderRoster(data.roster);}
    }
    function renderRoster(roster) {
        const el=root.querySelector('#ss-roster');if(!el)return;
        el.innerHTML=roster.length?roster.map(s=>`<label class="ss-check"><input type="checkbox" name="student" value="${s.id}" ${(!pendingTargets.length||pendingTargets.includes(s.id))?'checked':''}>${esc(s.username)}</label>`).join(''):'<p>Enroll students in this class before assigning a pack.</p>';
    }
    function renderPack() {
        shell(pack.title,`${pack.meta.grade} · ${pack.meta.subject} · ${pack.meta.language}`,btn('library','All packs')+(pack.owner?btn('duplicate','Duplicate'):'')+(!pack.editable?btn('export','Download study notes'):''));
        if(pack.editable)return editor();
        if(pack.teacherView) {
            body().innerHTML=`<div class="ss-note">Published version · learner assignments are frozen. Duplicate to make changes.</div><article class="ss-card"><h2>Approved teaching material</h2><ul class="ss-prose">${pack.content.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul><div id="ss-approved" class="ss-prose"></div>${Object.entries(pack.content.assessments).map(([stage,qs])=>`<details><summary>${labels[stage]} · teacher answer key</summary>${qs.map(q=>`<p><strong>${esc(q.prompt)}</strong></p><p>Answer: ${esc(q.options[q.correctIndex])}</p><p>${esc(q.explanation)}</p>`).join('')}</details>`).join('')}<div class="ss-actions">${btn('insights','View class evidence',true)}</div></article>`;
            prose(root.querySelector('#ss-approved'),pack.content.lesson+'\n\n'+pack.content.workedExample);return;
        }
        const baseline=pack.results.some(r=>r.stage==='baseline');
        body().innerHTML=`<div class="ss-note">${esc(pack.meta.sourceStatus)}${pack.classId?' · Teacher-approved pack':''}</div><div class="ss-split"><nav class="ss-steps" aria-label="Chapter activities">${[['learn','01 · Learn'],['cards','02 · Recall'],['practice','03 · Check'],['coach','04 · Explain'],['sources','Source material'],['progress','Your evidence']].map(([t,l])=>`<button class="ss-step" data-ss="pack-tab" data-tab="${t}" aria-current="${t===tab}">${l}</button>`).join('')}</nav><div id="ss-pack-content"></div></div>`;
        const el=root.querySelector('#ss-pack-content');
        if(!baseline&&!['sources','progress'].includes(tab)){assessment(el,'baseline');return;}
        if(tab==='learn') {
            el.innerHTML=`<article class="ss-card"><span class="ss-eyebrow">What you’ll understand</span><ul class="ss-prose">${pack.content.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul><hr style="border:0;border-top:1px solid var(--ss-line);margin:24px 0"><div class="ss-prose" id="ss-lesson"></div><details><summary>Work through an example</summary><div class="ss-prose" id="ss-example"></div></details><div class="ss-actions">${btn('read','Listen to lesson')}${btn('stop-audio','Stop audio')}${btn('video','Find a matching video')}${pack.content.lab?btn('lab','Explore the lab',false,`data-lab="${pack.content.lab}"`):''}</div></article>`;
            prose(el.querySelector('#ss-lesson'),pack.content.lesson);prose(el.querySelector('#ss-example'),pack.content.workedExample);
        } else if(tab==='cards')el.innerHTML=`<h2>Bring it back from memory.</h2><p>Say your answer before revealing the card. These cards are practice, not a mastery score.</p><div class="ss-two">${pack.content.cards.map((c,i)=>`<button class="ss-flip" data-ss="flip" data-card="${i}" aria-pressed="false"><span class="ss-eyebrow">${i+1} · Tap to reveal</span><div style="margin-top:14px">${esc(c.front)}</div></button>`).join('')}</div>`;
        else if(tab==='practice')assessment(el,pack.nextStage);
        else if(tab==='sources')el.innerHTML=`<article class="ss-card"><h2>${esc(pack.meta.sourceName)}</h2><p>${esc(pack.meta.edition||'No edition provided')}. ${esc(pack.meta.sourceStatus)}</p>${pack.meta.sourcePages.length?pack.meta.sourcePages.map(p=>`<details><summary>Source section ${p.page} · ${esc(p.method||'text')}</summary><div class="ss-prose">${esc(p.text)}</div></details>`).join(''):'<p>This is a general topic draft. No source document was supplied.</p>'}</article>`;
        else if(tab==='coach')coach(el);
        else progress(el);
    }
    function editor() {
        const c=pack.content;
        body().innerHTML=`<div class="ss-note">Private draft. Check source accuracy, teaching content and every answer key. Approval freezes this version.</div><form id="ss-editor" class="ss-form"><article class="ss-card ss-form"><h2>Review the lesson</h2><label>Learning objectives, one per line<textarea name="objectives" rows="3">${esc(c.objectives.join('\n'))}</textarea></label><label>Lesson<textarea name="lesson" rows="12">${esc(c.lesson)}</textarea></label><label>Worked example<textarea name="workedExample" rows="6">${esc(c.workedExample)}</textarea></label></article><details><summary>Revision cards and oral practice</summary><div class="ss-form">${c.cards.map((card,i)=>`<div class="ss-two">${field('card-front-'+i,'Card '+(i+1),card.front)}<label>Answer<textarea name="card-back-${i}" rows="2">${esc(card.back)}</textarea></label></div>`).join('')}<label>Oral questions, one per line<textarea name="viva" rows="4">${esc(c.viva.join('\n'))}</textarea></label></div></details>${Object.entries(c.assessments).map(([stage,qs])=>`<details><summary>${labels[stage]} · review ${qs.length} questions and answers</summary><div class="ss-form">${qs.map((q,i)=>`<fieldset class="ss-q"><legend>Question ${i+1}</legend><div class="ss-form"><label>Prompt<textarea name="${stage}-${i}-prompt" rows="2">${esc(q.prompt)}</textarea></label>${field(`${stage}-${i}-concept`,'Concept',q.concept)}${q.options.map((o,j)=>field(`${stage}-${i}-option-${j}`,'Option '+(j+1),o)).join('')}<label>Correct option<select name="${stage}-${i}-correct">${q.options.map((_,j)=>`<option value="${j}" ${q.correctIndex===j?'selected':''}>Option ${j+1}</option>`).join('')}</select></label><label>Explanation<textarea name="${stage}-${i}-explanation" rows="3">${esc(q.explanation)}</textarea></label><span class="ss-mini">${q.sourcePage?'Source section '+q.sourcePage+' · verify this reference':'AI-written question · no exact source citation'}</span></div></fieldset>`).join('')}</div></details>`).join('')}<div class="ss-actions"><button class="ss-btn" type="submit">Save reviewed edits</button></div></form><article class="ss-card" style="margin-top:24px"><h2>${pack.classId?'Assign to learners':'Begin personal practice'}</h2>${pack.classId?'<p>Choose the whole class or a targeted follow-up group.</p><div class="ss-form" id="ss-roster">Loading active learners…</div><label class="ss-label" style="margin-top:16px">Due date (optional)<input type="date" id="ss-due"></label>':''}<label class="ss-check" style="margin:20px 0"><input type="checkbox" id="ss-reviewed">I reviewed the source material, explanations and answer keys.</label>${btn('publish',pack.classId?'Approve and assign':'Approve and start',true)}</article>`;
        root.querySelector('#ss-editor').onsubmit=e=>{e.preventDefault();perform(e.submitter,()=>saveEdits());};
    }
    async function saveEdits() {
        const form=root.querySelector('#ss-editor');if(!form)return;
        const original=pack,version=viewVersion,f=new FormData(form),c=structuredClone(original.content);
        c.objectives=f.get('objectives').split('\n').map(s=>s.trim()).filter(Boolean);c.lesson=f.get('lesson');c.workedExample=f.get('workedExample');
        c.viva=f.get('viva').split('\n').map(s=>s.trim()).filter(Boolean);
        c.cards=c.cards.map((card,i)=>({front:f.get('card-front-'+i),back:f.get('card-back-'+i)}));
        for(const [stage,qs]of Object.entries(c.assessments))c.assessments[stage]=qs.map((q,i)=>({...q,prompt:f.get(`${stage}-${i}-prompt`),concept:f.get(`${stage}-${i}-concept`),options:q.options.map((_,j)=>f.get(`${stage}-${i}-option-${j}`)),correctIndex:Number(f.get(`${stage}-${i}-correct`)),explanation:f.get(`${stage}-${i}-explanation`)}));
        await request(`studio/packs/${original.id}/edit`,{version:original.version,content:c});
        if(version!==viewVersion||pack!==original)return false;
        original.content=c;original.version++;status('Edits saved. Review is ready for approval.');return true;
    }
    function assessment(el,stage) {
        if(!stage){el.innerHTML='<article class="ss-card"><h2>Four checks complete.</h2><p>Open Your evidence to compare your starting point, independent check and retention.</p></article>';return;}
        const qs=pack.content.assessments[stage];
        if(!qs){el.innerHTML=`<article class="ss-card"><span class="ss-eyebrow">Let learning settle</span><h2 style="margin-top:12px">Come back for your retention check.</h2><p>Opens ${esc(new Date(pack.retentionDue).toLocaleString())}, seven days after your independent check. Until then, revisit your lesson and cards.</p></article>`;return;}
        el.innerHTML=`<article class="ss-card"><span class="ss-eyebrow">${stage==='practice'?'Supported practice':'Your own understanding'}</span><h2 style="margin-top:10px">${labels[stage]}</h2><p>${stage==='baseline'?'Try these before reading the lesson. It is fine to skip what you have not learned yet.':stage==='practice'?'Use your lesson and notes if needed. Explanations appear after submission.':'Use what you remember, without notes or AI help. These are new questions, not repeats of practice.'}</p><form id="ss-assessment">${qs.map((q,i)=>`<fieldset class="ss-q"><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map((o,j)=>`<label class="ss-option"><input type="radio" name="answer-${i}" value="${j}" required>${esc(o)}</label>`).join('')}<label class="ss-option"><input type="radio" name="answer-${i}" value="skip" required>Skip for now</label></fieldset>`).join('')}${stage!=='practice'?'<label class="ss-check" style="margin-bottom:20px"><input name="unassisted" type="checkbox" required>I attempted this check without notes or AI assistance.</label>':''}<button class="ss-btn ss-primary">Submit check</button><p class="ss-mini">Practice evidence only. No official school grade or mastery claim.</p></form></article>`;
        el.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=pack.id,version=viewVersion;perform(e.submitter,async()=>{await request(`studio/packs/${id}/attempts`,{stage,answers:qs.map((_,i)=>f.get('answer-'+i)==='skip'?null:Number(f.get('answer-'+i))),unassisted:f.get('unassisted')==='on'});if(version!==viewVersion)return;await showPack(id);if(pack?.id!==id)return;tab='progress';renderPack();status('Your check and explanations are saved.');});};
    }
    function progress(el) {
        const base=pack.results.find(r=>r.stage==='baseline'),follow=pack.results.find(r=>r.stage==='followup');
        el.innerHTML=`<h2>Evidence of your progress</h2><p>Four different checks of the same objectives. Scores describe these questions, not your entire ability.</p><div class="ss-grid">${pack.results.map(r=>`<article class="ss-card"><span class="ss-eyebrow">${labels[r.stage]}</span><div class="ss-stat">${r.score}/${r.total}</div><span class="ss-mini">${esc(new Date(r.createdAt).toLocaleDateString())}</span></article>`).join('')}</div>${base&&follow?`<div class="ss-note">Starting → independent check: ${base.percent}% → ${follow.percent}%. Different questions; improvement on a small set is not proof of lasting mastery.</div>`:''}${pack.results.map(r=>`<details><summary>${labels[r.stage]} · review your answers</summary><p class="ss-mini">${esc(r.condition)}</p>${r.results.map(q=>`<div class="ss-source-page"><strong>${q.correct?'Correct':'Revisit'} · ${esc(q.concept)}</strong><p>${esc(q.prompt)}</p><div class="ss-prose">${esc(q.explanation)}</div></div>`).join('')}</details>`).join('')}${pack.nextStage?btn('next-check','Continue to '+labels[pack.nextStage],true):''}`;
    }
    function coach(el) {
        el.innerHTML=`<article class="ss-card"><h2>Explain it. Make it yours.</h2><p>Share your working or explain an idea in your own words. Start with a hint, then retry before asking for the full method.</p><form id="ss-coach" class="ss-form"><label>Practice type<select name="kind"><option value="working">Check my working</option><option value="viva">Oral / teach-back practice</option></select></label><label>Question<select id="ss-viva-pick"><option value="">Write my own question</option>${pack.content.viva.map((q,i)=>`<option value="${i}">${esc(q)}</option>`).join('')}</select><textarea name="question" id="ss-coach-question" rows="2" required maxlength="2000" placeholder="The problem or idea you are explaining"></textarea></label><label>Your working or corrected transcript<textarea name="response" id="ss-coach-response" rows="7" required maxlength="6000" placeholder="Show your steps, including where you got stuck."></textarea></label><label>Photo or document of your working<input id="ss-working-file" type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.txt,.docx"></label>${btn('extract-working','Read my working')}<div class="ss-actions">${btn('dictate','Dictate my explanation')}${btn('stop-dictation','Stop dictation')}</div><p class="ss-mini">Dictation depends on browser support and may use your browser’s speech service. Review the transcript before sending. Your accent is not graded.</p><div class="ss-actions"><button class="ss-btn ss-primary" name="level" value="hint">Give me one hint</button><button class="ss-btn" name="level" value="explain">Explain the method</button></div></form></article><div id="ss-feedback"></div>${pack.coaching.map(c=>`<details><summary>${esc(c.kind==='viva'?'Oral practice':'Working review')} · ${esc(new Date(c.created_at).toLocaleDateString())}</summary><p>${esc(c.question)}</p><div class="ss-prose">${esc(c.feedback)}</div>${c.teacher_feedback?`<div class="ss-note"><strong>Teacher feedback</strong><p>${esc(c.teacher_feedback)}</p></div>`:''}</details>`).join('')}`;
        el.querySelector('#ss-viva-pick').onchange=e=>{if(e.target.value!=='')el.querySelector('#ss-coach-question').value=pack.content.viva[Number(e.target.value)];};
        el.querySelector('form').onsubmit=e=>{e.preventDefault();recognition?.stop();const f=new FormData(e.currentTarget),level=e.submitter.value,id=pack.id,version=viewVersion;perform(e.submitter,async()=>{const r=await request(`studio/packs/${id}/coach`,{...Object.fromEntries(f),level});if(version!==viewVersion)return;pack.coaching.unshift({id:r.id,kind:f.get('kind'),question:f.get('question'),response:f.get('response'),feedback:r.feedback,created_at:new Date().toISOString()});const out=root.querySelector('#ss-feedback');out.innerHTML='<article class="ss-card" style="margin-top:20px"><span class="ss-eyebrow">AI practice feedback · teacher can review</span><div class="ss-prose"></div></article>';prose(out.querySelector('.ss-prose'),r.feedback);status('Feedback saved. Try a correction in your working above.');});};
    }
    async function sources() {
        const version=++viewVersion;if(!selectedClass)throw new Error('Choose a classroom first.');
        shell('Sources you can trust.','Upload, extract, inspect, correct. Your files start private.',btn('library','Back to packs'));
        const {resources}=await request(`studio/classes/${selectedClass}/sources`);if(version!==viewVersion)return;
        body().innerHTML=`<article class="ss-card"><form id="ss-upload" class="ss-form"><label>Add a teaching resource<input name="file" type="file" required></label><p class="ss-mini">Any attachment up to 6 MB. AI extraction: PDF, JPG, JPEG, PNG, WebP, DOCX, PPTX and text. Files are downloaded as attachments; malware scanning is not configured.</p><button class="ss-btn ss-primary" style="width:fit-content">Upload privately</button></form></article><div class="ss-card" style="margin-top:20px">${resources.length?resources.map(r=>`<div class="ss-row"><div><strong>${esc(r.name)}</strong><p class="ss-mini" style="margin:4px 0">${esc(r.status||'Attachment · not extracted')} · ${(r.bytes/1024).toFixed(1)} KB</p>${r.warning?`<span class="ss-mini">${esc(r.warning)}</span>`:''}</div><div class="ss-actions">${['queued','processing'].includes(r.status)?btn('sources','Refresh status'):r.status?btn('source-review','Review text',false,`data-id="${r.id}"`):btn('extract','Extract text',false,`data-id="${r.id}"`)}</div></div>`).join(''):'<p>No resources in this classroom yet.</p>'}</div>`;
        root.querySelector('#ss-upload').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const selected=selectedClass,version=viewVersion,file=root.querySelector('input[type=file]').files[0];if(!file||file.size>6*1024*1024||!file.size)throw new Error('Choose a nonempty file up to 6 MB.');const data=await readFile(file);const r=await request(`teaching-studio/classes/${selected}/resources`,{name:file.name,data});await request(`studio/classes/${selected}/sources/${r.id}/extract`,{});if(version!==viewVersion)return;await sources();status('Uploaded privately. Extraction continues in the background; refresh to review.');});};
    }
    const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('Could not read this file.'));r.readAsDataURL(file);});
    async function reviewSource(id) {
        const version=++viewVersion,selected=selectedClass;
        const s=await request(`studio/classes/${selected}/sources/${id}`);if(version!==viewVersion)return;
        source=s;shell(s.name,'Correct the extraction before it becomes learning material.',btn('sources','Back to sources'));
        if(['processing','queued'].includes(s.status)){body().innerHTML='<div class="ss-note">Extraction is still running. Return to sources and refresh its status.</div>';return;}
        if(!s.pages.length)s.pages=[{page:1,text:''}];
        body().innerHTML=`<div class="ss-note">${esc(s.warning)}</div><form id="ss-source-edit" class="ss-form">${s.pages.map(p=>`<article class="ss-card"><label class="ss-label">Source section ${p.page}${p.confidence!=null?' · OCR confidence '+p.confidence+'%':''}<textarea name="page-${p.page}" rows="8">${esc(p.text)}</textarea></label><p class="ss-mini">${p.text?'Check equations, diagrams and names.':'No text read here. Paste the missing material or leave it blank.'}</p></article>`).join('')}<button class="ss-btn ss-primary">Save reviewed extraction</button></form>`;
        root.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(e.submitter,async()=>{await request(`studio/classes/${selected}/sources/${id}/review`,{version:s.version,pages:s.pages.map(p=>({page:p.page,text:f.get('page-'+p.page)}))});await sources();status('Reviewed text saved. Existing published packs keep their original source version.');});};
    }
    async function insights() {
        const version=++viewVersion;if(!selectedClass)throw new Error('Choose a classroom first.');
        const data=await request(`studio/classes/${selectedClass}/insights`);if(version!==viewVersion)return;
        shell('See the next teaching step.','Review evidence, support a group, then check again.',btn('library','Back to packs')+btn('impact-export','Export aggregate report'));
        const x=data.impact;
        body().innerHTML=`<div class="ss-grid">${[[x.matchedChecks,'Matched starting / follow-up checks'],[x.averageChangePoints==null?'—':(x.averageChangePoints>0?'+':'')+x.averageChangePoints+' pp','Average score change'],[x.retainedChecks,'Completed delayed checks']].map(([n,l])=>`<article class="ss-card"><div class="ss-stat">${n}</div><span class="ss-mini">${l}</span></article>`).join('')}</div><div class="ss-note">${esc(x.note)} ${x.missingFollowups} starting checks are awaiting follow-up.</div><h2 style="margin-top:28px">Concepts to revisit</h2><div class="ss-grid">${data.concepts.filter(c=>c.misses).map((c,i)=>`<article class="ss-card"><span class="ss-pill">${esc(c.signal)}</span><h3 style="margin-top:14px">${esc(c.concept)}</h3><p>${c.misses} missed answers across ${c.checks} questions in the latest independent check per learner and pack. ${c.students.length} active learners involved.</p><details><summary>See question evidence</summary>${c.evidence.map(e=>`<p>${esc(e.question)} <span class="ss-mini">· ${labels[e.stage]}</span></p>`).join('')}</details>${btn('targeted','Prepare follow-up',false,`data-concept="${i}"`)}</article>`).join('')||'<article class="ss-card"><p>Patterns appear after learners complete assigned checks. No difficulties inferred yet.</p></article>'}</div><h2 style="margin-top:28px">Practice feedback to review</h2>${data.coaching.map(c=>`<details><summary>${esc(c.username)} · ${esc(c.title)} ${c.teacher_feedback?'· reviewed':''}</summary><p><strong>${esc(c.question)}</strong></p><div class="ss-prose">${esc(c.response)}</div><details><summary>AI feedback</summary><div class="ss-prose">${esc(c.feedback)}</div></details><label class="ss-label">Your feedback<textarea data-review-text="${c.id}" rows="3" maxlength="5000">${esc(c.teacher_feedback||'')}</textarea></label><div class="ss-actions" style="margin-top:12px">${btn('teacher-review','Save teacher feedback',true,`data-id="${c.id}"`)}</div></details>`).join('')||'<p>No submitted working or oral practice yet.</p>'}`;
        root.querySelector('[data-ss="impact-export"]').onclick=()=>download(JSON.stringify(x,null,2),'learning-impact.json');
        const concepts=data.concepts.filter(c=>c.misses);
        root.querySelectorAll('[data-ss="targeted"]').forEach(b=>b.onclick=()=>{const c=concepts[Number(b.dataset.concept)];pendingTargets=c.students;createForm({title:c.concept+' · follow-up',sourceText:'Create a fresh explanation and varied practice for this concept: '+c.concept+'. Include prerequisite checks and avoid labeling learners. Prior questions to vary: '+c.evidence.map(e=>e.question).join('\n')});});
    }
    async function perform(button,work) {
        button.disabled=true;try{await work();}catch(e){if(account===token()&&button.isConnected)status(e.message,true);}finally{button.disabled=false;}
    }
    async function action(button) {
        const a=button.dataset.ss;
        if(a==='library')return library();if(a==='new')return createForm();if(a==='pack')return showPack(button.dataset.id);
        if(a==='sources')return sources();if(a==='insights')return insights();if(a==='source-review')return reviewSource(button.dataset.id);
        if(a==='extract-personal'||a==='extract-working') {
            const file=root.querySelector(a==='extract-personal'?'#ss-source-file':'#ss-working-file').files[0];
            if(!file||!file.size||file.size>6*1024*1024)throw new Error('Choose a nonempty file up to 6 MB.');
            const version=viewVersion;status('Reading the document. You will be able to correct the text…');
            const r=await request('studio/extract-preview',{name:file.name,data:await readFile(file)});if(version!==viewVersion)return;
            if(r.status!=='ready')throw new Error(r.warning);
            const text=r.pages.map(p=>p.text).join('\n\n'),limit=a==='extract-personal'?24000:6000;
            root.querySelector(a==='extract-personal'?'textarea[name=sourceText]':'#ss-coach-response').value=text.slice(0,limit);
            status('Text extracted. Correct any OCR errors before sending. '+(text.length>limit?'Only the first '+limit+' characters were copied. ':'')+r.warning);return;
        }
        if(a==='extract'){await request(`studio/classes/${selectedClass}/sources/${button.dataset.id}/extract`,{});return sources();}
        if(a==='pack-tab'){++viewVersion;tab=button.dataset.tab;recognition?.stop();return renderPack();}
        if(a==='next-check'){tab='practice';return renderPack();}
        if(a==='publish') {
            if(!root.querySelector('#ss-reviewed').checked)throw new Error('Review the content and check the approval box first.');
            const students=[...root.querySelectorAll('input[name=student]:checked')].map(i=>Number(i.value)),dueDate=root.querySelector('#ss-due')?.value;
            const original=pack,version=viewVersion;
            if(!await saveEdits())return;
            await request(`studio/packs/${original.id}/publish`,{version:original.version,reviewed:true,students,dueDate});
            if(version!==viewVersion)return;
            pendingTargets=[];await showPack(original.id);status('Approved version saved. '+(original.classId?'Assigned learners can now open it.':'Begin with your starting check.'));return;
        }
        if(a==='duplicate'){const version=viewVersion,r=await request(`studio/packs/${pack.id}/duplicate`,{});if(version===viewVersion)return showPack(r.id);return;}
        if(a==='flip'){const back=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(back));const c=pack.content.cards[Number(button.dataset.card)];button.querySelector('div').textContent=back?c.back:c.front;button.querySelector('span').textContent=back?'Answer · tap to return':'Recall · tap to reveal';return;}
        if(a==='labs'||a==='lab'){switchPortal('student',false);navigateToSection('learning-labs');if(a==='lab')window.LearningLabs?.show(button.dataset.lab);return;}
        if(a==='video'){switchPortal('student',false);navigateToSection('ai-chat');const input=document.getElementById('grok-chat-input');input.value=`Suggest a full lesson video for ${pack.meta.board} ${pack.meta.grade} ${pack.meta.subject}: ${pack.title}. Spoken language: ${pack.meta.language}. Book/edition: ${pack.meta.edition||'not supplied'}. Explain the match and say what coverage you could verify.`;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();return;}
        if(a==='read'){if(!window.speechSynthesis)throw new Error('Audio playback is not available in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(pack.content.lesson);u.lang=/hindi|hinglish/i.test(pack.meta.language)?'hi-IN':'en-IN';speechSynthesis.speak(u);return;}
        if(a==='stop-audio'){window.speechSynthesis?.cancel();return;}
        if(a==='dictate') {
            const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)throw new Error('Dictation is unavailable in this browser. Type your explanation or use your device keyboard microphone.');
            recognition?.stop();recognition=new Recognition();recognition.lang=/hindi|hinglish/i.test(pack.meta.language)?'hi-IN':'en-IN';recognition.continuous=true;recognition.interimResults=false;
            const field=root.querySelector('#ss-coach-response');recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)field.value=(field.value+' '+e.results[i][0].transcript).slice(0,6000);};recognition.onerror=()=>status('Dictation stopped. You can edit or type the transcript.',true);recognition.start();status('Listening. Stop when finished, then review the transcript.');return;
        }
        if(a==='stop-dictation'){recognition?.stop();status('Review the transcript before requesting feedback.');return;}
        if(a==='teacher-review'){await request(`studio/classes/${selectedClass}/coaching/${button.dataset.id}/review`,{feedback:root.querySelector(`[data-review-text="${button.dataset.id}"]`).value});status('Teacher feedback saved for the learner.');return;}
        if(a==='export') {
            const c=pack.content;if(!pack.teacherView&&!pack.results.some(r=>r.stage==='baseline'))throw new Error('Complete the starting check before downloading lesson notes.');
            const text=[pack.title,pack.meta.sourceStatus,'\nOBJECTIVES',...c.objectives,'\nLESSON',c.lesson,'\nWORKED EXAMPLE',c.workedExample,'\nREVISION CARDS',...c.cards.map(x=>x.front+'\n'+x.back)].join('\n\n');download(text,'study-pack.txt','text/plain');return;
        }
    }
    for(const id of ['ss-student','ss-teacher'])document.getElementById(id).addEventListener('click',e=>{const b=e.target.closest('[data-ss]');if(b&&!['impact-export','targeted'].includes(b.dataset.ss))perform(b,()=>action(b));});
    function installMemory() {
        const side=document.getElementById('grok-side');if(!side)return;
        const details=document.createElement('details');details.className='ss-memory';details.innerHTML='<summary>What my Companion remembers</summary><div class="ss-root" id="ss-memory-body"></div>';side.querySelector('[data-side-panel="memory"]').prepend(details);
        details.addEventListener('toggle',async()=>{if(!details.open)return;const el=details.querySelector('div');el.textContent='Loading preferences…';try{const {facts}=await request('ai/memory');el.innerHTML=`<p class="ss-mini">Saved across chats. Your latest message takes priority. Conversation history is managed separately.</p>${facts.map((f,i)=>`<div class="ss-row"><div><strong>${esc(({video_language:'Video language',explanation_language:'Explanation language',class:'Class',board:'Board',answer_detail:'Answer length'})[f.mem_key]||f.mem_key.replaceAll('_',' '))}</strong><p class="ss-mini">${esc(f.mem_value)}</p></div><button class="ss-link" data-forget="${i}">Forget</button></div>`).join('')}<form class="ss-form" style="margin-top:14px"><label>Preference<select name="key"><option value="video_language">Video spoken language</option><option value="explanation_language">Explanation language</option><option value="class">Class</option><option value="board">Board</option><option value="answer_detail">Answer length</option></select></label><label>Remember<input name="value" maxlength="400" required placeholder="e.g. Hindi / Hinglish"></label><button class="ss-btn">Save preference</button><p class="ss-mini" role="status"></p></form>`;el.querySelectorAll('[data-forget]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await request('ai/memory/'+encodeURIComponent(facts[Number(b.dataset.forget)].mem_key),undefined,'DELETE');b.closest('.ss-row').remove();}catch(e){el.querySelector('[role=status]').textContent=e.message;b.disabled=false;}});el.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;b.disabled=true;try{await request('ai/memory',Object.fromEntries(f));details.open=false;details.open=true;}catch(e){el.querySelector('[role=status]').textContent=e.message;}finally{b.disabled=false;}};}catch(e){el.textContent=e.message;}});
    }
    window.StudyStudio={open,request,close:()=>{++viewVersion;recognition?.stop();window.speechSynthesis?.cancel();},openPack:id=>{queuedPack=id;navigateToSection('study-studio');}};installMemory();
    const start=()=>{if(document.getElementById('study-studio').classList.contains('active'))open(false);if(document.getElementById('teacher-tab-learning').classList.contains('active'))open(true);};
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
    window.addEventListener('storage',e=>{if(e.key==='authToken'){++viewVersion;pack=null;account='';recognition?.stop();document.querySelectorAll('#ss-student,#ss-teacher,#ss-memory-body').forEach(e=>e.replaceChildren());}});
})();
