const { test } = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const jwt = require('jsonwebtoken');
const db = require('../config/db');
const ai = require('../services/ai');

test('Teaching Studio keeps files private, controls publication, and validates class attendance', async t => {
    await db.ready();
    const app = express(); app.use(express.json({ limit:'10mb' }));
    app.use('/api/teaching-studio', require('../controllers/teachingStudioController'));
    const server = app.listen(0,'127.0.0.1');
    await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
    t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
    const base = `http://127.0.0.1:${server.address().port}/api/teaching-studio`;
    async function user(name,role) {
        const result = await db.run('INSERT INTO users (username,password,role) VALUES (?, ?, ?)', [name,'unused',role]);
        return { id:result.lastID, token:jwt.sign({user:{id:result.lastID,role}}, process.env.JWT_SECRET) };
    }
    const teacher = await user('studio-teacher','teacher'), student = await user('studio-student','student'), outsider = await user('studio-outsider','student');
    const c = await db.run("INSERT INTO classrooms (name,section,class_code,created_by,status) VALUES ('Studio class','A','STUDIO',?,'active')",[teacher.id]);
    const classId = c.lastID;
    await db.run("INSERT INTO teacher_classes (class_id,teacher_id,role) VALUES (?,?,'owner')",[classId,teacher.id]);
    await db.run("INSERT INTO class_enrollments (class_id,student_id,status) VALUES (?,?,'active')",[classId,student.id]);
    const call = (path, u, body) => fetch(base + path,{method:body === undefined ? 'GET':'POST',headers:{Authorization:`Bearer ${u.token}`,'Content-Type':'application/json'},...(body === undefined ? {}:{body:JSON.stringify(body)})});
    const prefix = `/classes/${classId}`;
    assert.equal((await call(prefix,student)).status,403);
    assert.equal((await call(prefix,teacher)).status,200);
    assert.equal((await call(prefix+'/resources',teacher,{name:'../escape.txt',data:'YQ=='})).status,400);
    assert.equal((await call(prefix+'/resources',teacher,{name:'empty.txt',data:''})).status,400);
    const upload = await call(prefix+'/resources',teacher,{name:'worksheet.txt',data:Buffer.from('Fractions represent parts of a whole.').toString('base64')});
    assert.equal(upload.status,201); const file = await upload.json(); assert.equal(file.readable,true);
    const link = prefix+`/resources/${file.id}/download`;
    assert.equal((await call(link,student)).status,403);
    const ownDownload = await call(link,teacher);
    assert.match(ownDownload.headers.get('content-disposition'),/^attachment/);
    assert.equal(ownDownload.headers.get('x-content-type-options'),'nosniff');
    assert.equal(await ownDownload.text(),'Fractions represent parts of a whole.');
    assert.equal((await call(prefix+`/resources/${file.id}/share`,teacher,{shared:true})).status,200);
    assert.equal((await call(link,student)).status,200);
    assert.equal((await call(link,outsider)).status,403);
    assert.equal((await (await call('/student/resources',student)).json()).resources.length,1);
    await db.run("UPDATE class_enrollments SET status = 'blocked' WHERE class_id = ? AND student_id = ?",[classId,student.id]);
    assert.equal((await call(link,student)).status,403);
    await db.run("UPDATE class_enrollments SET status = 'active' WHERE class_id = ? AND student_id = ?",[classId,student.id]);
    const day = new Date().toISOString().slice(0,10);
    assert.equal((await call(prefix+'/attendance',teacher,{day,entries:[]})).status,400);
    assert.equal((await call(prefix+'/attendance',teacher,{day,entries:[{studentId:outsider.id,status:'present'}]})).status,400);
    assert.equal((await call(prefix+'/attendance',teacher,{day,entries:[{studentId:student.id,status:'absent'}]})).status,200);
    assert.equal((await call(prefix+'/attendance',teacher,{day,entries:[{studentId:student.id,status:'present'}]})).status,200);
    assert.equal((await db.get('SELECT COUNT(*) AS n FROM teaching_attendance')).n,1);
    const original = ai.generateText; ai.generateText = async () => 'Teacher-reviewed lesson\nPractice: Explain one half.';
    t.after(() => { ai.generateText = original; });
    const draftResponse = await call(prefix+'/drafts/generate',teacher,{kind:'lesson',title:'Fractions',instructions:'Grade 5',resourceId:file.id});
    assert.equal(draftResponse.status,201); const draft = await draftResponse.json();
    assert.equal((await call(prefix+`/drafts/${draft.id}`,outsider,{content:'hijack',version:1,publish:true})).status,403);
    assert.equal((await call(prefix+`/drafts/${draft.id}`,teacher,{content:'Approved lesson',version:1,publish:true})).status,200);
    assert.equal((await call(prefix+`/drafts/${draft.id}`,teacher,{content:'Duplicate',version:1,publish:true})).status,409);
    assert.equal((await db.get('SELECT COUNT(*) AS n FROM class_notes WHERE class_id = ?',[classId])).n,1);
    const parent = await (await call(prefix+'/drafts/generate',teacher,{kind:'parent',title:'Weekly update',instructions:'No scores recorded.'})).json();
    assert.equal((await call(prefix+`/drafts/${parent.id}`,teacher,{content:'Private',version:1,publish:true})).status,400);
    const html = await (await call(prefix+'/resources',teacher,{name:'demo.html',data:Buffer.from('<script>alert(1)</script>').toString('base64')})).json();
    assert.equal(html.readable,false);
    assert.equal((await call(prefix+'/drafts/generate',teacher,{kind:'lesson',title:'Bad source',instructions:'Read it',resourceId:html.id})).status,400);
    const state = await (await call(prefix,teacher)).json();
    assert.equal(state.impact.attendancePresent,1); assert.equal(state.impact.averageScore,null);
    assert.equal(JSON.stringify(state.impact).includes('studio-student'),false);
    await db.run("UPDATE users SET role = 'student' WHERE id = ?",[teacher.id]);
    assert.equal((await call(prefix,teacher)).status,403);
    assert.equal((await call(link,teacher)).status,403);
});
