'use strict';
// Additive, versioned migration. VARCHAR timestamps are avoided: all payment
// times are UTC milliseconds, identical on SQLite and MySQL. Financial rows
// retain their owner and prevent deleting an account with accounting history.
module.exports = async function up(db) {
 const tables = {
 payment_orders: `id VARCHAR(40) PRIMARY KEY, user_id INTEGER NOT NULL, mode VARCHAR(8) NOT NULL, provider VARCHAR(20) NOT NULL, plan_id VARCHAR(30) NOT NULL, product_name VARCHAR(100) NOT NULL, subtotal INTEGER NOT NULL, discount INTEGER NOT NULL, tax INTEGER NOT NULL, amount INTEGER NOT NULL, currency VARCHAR(3) NOT NULL, coupon VARCHAR(40), customer_name VARCHAR(160), customer_email VARCHAR(254), status VARCHAR(30) NOT NULL, idempotency_key VARCHAR(100) NOT NULL, fingerprint VARCHAR(64) NOT NULL, provider_order_id VARCHAR(100), provider_state VARCHAR(30), risk_decision VARCHAR(12) NOT NULL, ip_hash VARCHAR(64), device_hash VARCHAR(64), created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, paid_at BIGINT, last_checked_at BIGINT DEFAULT 0, UNIQUE(user_id,mode,idempotency_key), UNIQUE(provider,mode,provider_order_id), FOREIGN KEY(user_id) REFERENCES users(id)`,
 payment_sessions: `id VARCHAR(40) PRIMARY KEY, order_id VARCHAR(40) NOT NULL, method VARCHAR(30) NOT NULL, bank VARCHAR(40), status VARCHAR(30) NOT NULL, created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_transactions: `id VARCHAR(40) PRIMARY KEY, order_id VARCHAR(40) NOT NULL, user_id INTEGER NOT NULL, provider VARCHAR(20) NOT NULL, mode VARCHAR(8) NOT NULL, provider_reference VARCHAR(100) NOT NULL, amount INTEGER NOT NULL, currency VARCHAR(3) NOT NULL, method VARCHAR(30), status VARCHAR(30) NOT NULL, authorization_reference VARCHAR(120), risk_decision VARCHAR(12) NOT NULL, created_at BIGINT NOT NULL, paid_at BIGINT, UNIQUE(provider,mode,provider_reference), FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_attempts: `id VARCHAR(40) PRIMARY KEY, order_id VARCHAR(40) NOT NULL, user_id INTEGER NOT NULL, mode VARCHAR(8) NOT NULL, session_id VARCHAR(40), status VARCHAR(30) NOT NULL, method VARCHAR(30), ip_hash VARCHAR(64), device_hash VARCHAR(64), created_at BIGINT NOT NULL, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_methods: `id VARCHAR(30) NOT NULL, mode VARCHAR(8) NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, label VARCHAR(60) NOT NULL, PRIMARY KEY(id,mode)`,
 payment_refunds: `id VARCHAR(40) PRIMARY KEY, transaction_id VARCHAR(40) NOT NULL, order_id VARCHAR(40) NOT NULL, amount INTEGER NOT NULL, reason VARCHAR(500) NOT NULL, status VARCHAR(30) NOT NULL, provider_reference VARCHAR(100), idempotency_key VARCHAR(100) NOT NULL, requested_by INTEGER NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, test_outcome VARCHAR(20), UNIQUE(transaction_id,idempotency_key), UNIQUE(provider_reference), FOREIGN KEY(transaction_id) REFERENCES payment_transactions(id)`,
 payment_invoices: `id VARCHAR(40) PRIMARY KEY, number VARCHAR(60) NOT NULL UNIQUE, order_id VARCHAR(40) NOT NULL UNIQUE, transaction_id VARCHAR(40) NOT NULL, user_id INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at BIGINT NOT NULL, email_sent_at BIGINT, email_claimed_at BIGINT, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_subscriptions: `id VARCHAR(40) PRIMARY KEY, user_id INTEGER NOT NULL, mode VARCHAR(8) NOT NULL, plan_id VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, current_order_id VARCHAR(40) NOT NULL, starts_at BIGINT NOT NULL, ends_at BIGINT NOT NULL, cancel_at_period_end INTEGER DEFAULT 0, next_plan_id VARCHAR(30), updated_at BIGINT NOT NULL, UNIQUE(user_id,mode), FOREIGN KEY(user_id) REFERENCES users(id)`,
 payment_entitlements: `order_id VARCHAR(40) PRIMARY KEY, user_id INTEGER NOT NULL, mode VARCHAR(8) NOT NULL, plan_id VARCHAR(30) NOT NULL, starts_at BIGINT NOT NULL, ends_at BIGINT NOT NULL, revoked INTEGER DEFAULT 0, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_webhook_events: `id VARCHAR(120) PRIMARY KEY, provider VARCHAR(20) NOT NULL, mode VARCHAR(8) NOT NULL, order_id VARCHAR(40), event_type VARCHAR(100), body_hash VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL, received_at BIGINT NOT NULL, processed_at BIGINT`,
 payment_risk_assessments: `id VARCHAR(40) PRIMARY KEY, order_id VARCHAR(40) NOT NULL, score INTEGER NOT NULL, decision VARCHAR(12) NOT NULL, rules TEXT NOT NULL, reviewed_by INTEGER, reviewed_at BIGINT, note VARCHAR(500), created_at BIGINT NOT NULL, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 payment_audit_logs: `id VARCHAR(40) PRIMARY KEY, actor_id INTEGER, action VARCHAR(80) NOT NULL, entity_id VARCHAR(120), mode VARCHAR(8) NOT NULL, metadata TEXT NOT NULL, ip_hash VARCHAR(64), created_at BIGINT NOT NULL`,
 payment_reconciliation_records: `id VARCHAR(40) PRIMARY KEY, order_id VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, note VARCHAR(500), checked_by INTEGER, created_at BIGINT NOT NULL, FOREIGN KEY(order_id) REFERENCES payment_orders(id)`,
 };
 for(const [table,columns] of Object.entries(tables)) await db.run(`CREATE TABLE IF NOT EXISTS ${table} (${columns})${db.dialect()==='mysql'?' ENGINE=InnoDB':''}`);
 const indexes = [
 ['orders_owner','payment_orders','user_id,mode,created_at'],['orders_status','payment_orders','status,created_at'],['orders_ip','payment_orders','ip_hash,created_at'],['orders_device','payment_orders','device_hash,created_at'],
 ['sessions_order','payment_sessions','order_id,expires_at'],['transactions_order','payment_transactions','order_id,status'],['transactions_user','payment_transactions','user_id,created_at'],['transactions_method','payment_transactions','method,created_at'],
 ['attempts_user','payment_attempts','user_id,created_at'],['attempts_ip','payment_attempts','ip_hash,created_at'],['refunds_order','payment_refunds','order_id,status'],['invoices_user','payment_invoices','user_id,created_at'],['webhooks_order','payment_webhook_events','order_id,received_at'],['risk_order','payment_risk_assessments','order_id,created_at'],['audit_entity','payment_audit_logs','entity_id,created_at'],['recon_order','payment_reconciliation_records','order_id,created_at']
 ];
 for(const [name,table,columns] of indexes) {
   if(db.dialect()==='mysql') { if(!(await db.all(`SHOW INDEX FROM ${table} WHERE Key_name = ?`,['pay_'+name])).length) await db.run(`CREATE INDEX pay_${name} ON ${table} (${columns})`); }
   else await db.run(`CREATE INDEX IF NOT EXISTS pay_${name} ON ${table} (${columns})`);
 }
 for(const mode of ['test','live']) for(const [id,label] of Object.entries({upi:'UPI',card:'Card',netbanking:'Net banking',bank_transfer:'Bank transfer',wallet:'Wallet',emi:'EMI',paylater:'Pay later'})) await db.run('INSERT IGNORE INTO payment_methods (id,mode,enabled,label) VALUES (?,?,?,?)',[id,mode,1,label]);
};
